### ISSUE TITLE
Error : No such file or directory

### ISSUE THREAD

**Issue by dag-io** [bitrise-steplib/steps-cache-push#2]
### Context 

It's an Android project.
The build is available here : https://www.bitrise.io/build/e63b553468dc432c

### Config

```
    - cache-push@0.9.3:
        inputs:
        - cache_paths: "./.gradle"
        - fingerprint_method: file-mod-time
        - is_debug_mode: 'true'
```

### Error

```
rsync: change_dir "/root/.stepman/step_collections/1461397589/collection/steps/cache-push/0.9.3" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
FATA[20:21:03] [STEPMAN] - Failed to copy step.yml: exit status 23 
```
