### ISSUE TITLE
Cache pull & push fails due to missing cache URL

### ISSUE THREAD

**Issue by AvdLee** [bitrise-steplib/steps-cache-push#38]
I'm using a shared Bitrise.yml across repositories that include both a push and pull cache step. For most of my repos this is working fine but for one of them it's not:

```
+------------------------------------------------------------------------------+
| (6) cache-push@2.2.3                                                         |
+------------------------------------------------------------------------------+
| id: cache-push                                                               |
| version: 2.2.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-01-16T15:34:19Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
failed to parse config:
- CacheAPIURL: required variable is not present
Config:
- Paths: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/cache140249005
.build
/usr/local/Cellar/swiftlint
/usr/local/opt/swiftlint
/usr/local/Cellar/danger-swift
/usr/local/opt/danger-swift
/usr/local/Cellar/danger-js
/usr/local/opt/danger-js
$ GEM_CACHE_PATH
./vendor-> ./Gemfile.lock #gem installation directory
- IgnoredPaths: 
- CacheAPIURL: 
- FingerprintMethodID: file-content-hash
- CompressArchive: false
- DebugMode: true
- StackID: osx-xcode-11.3.x
WARN[15:34:25] Step (cache-push@2.2.3) failed, but was marked as skippable 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ! | cache-push@2.2.3 (exit code: 1)                               | 6.65 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-cache-push/issues    |
| Source: https://github.com/bitrise-steplib/steps-cache-push.git              |
+---+---------------------------------------------------------------+----------+
```

This is kind of weird to me as the cache URL is set by Bitrise. 

Any idea what can cause this to happen?

Build is open and can be found here: https://app.bitrise.io/build/f754f352f10c2f7d#?tab=log

**Comment by non-binary** [comment]
Hi @AvdLee,

Thank you for reaching out.

You mentioned that you have other projects that this isn't a problem in. Can you share a log from one of these projects so that I can compare the two logs?

Thanks, looking forward to hearing from you.
Luna

[full log from red build](https://github.com/bitrise-steplib/steps-cache-push/files/4078547/f754f352f10c2f7d.log)

**Comment by AvdLee** [comment]
@non-binary yes, absolutely. Here you go:

[Full log from green build](https://github.com/bitrise-steplib/steps-cache-push/files/4085654/ade3a5b37da6cfe5.log)

**Comment by AvdLee** [comment]
Interesting, I decided to go for my own comparison as well and found out this difference:

![image](https://user-images.githubusercontent.com/4329185/72718954-3a17b280-3b77-11ea-9a44-2ec0147bddcc.png)

The `activate-ssh-key` step for the failing build is not triggered. I'll try to enable that and see if it works!

**Comment by AvdLee** [comment]
I've looked at a few more of my repos that are all public and they all seem to fail for the caching steps. Does it mean that caching is not available for public repositories?

**Comment by non-binary** [comment]
I've created this diff: https://www.diffchecker.com/JDod7r2g. I'm going to talk with my colleagues and see what they suggest. Thanks for your patience.

**Comment by non-binary** [comment]
@AvdLee: Can you share your bitrise.yml file of a working project and the non-working project? You are also caching CocoaPods correct?

**Comment by AvdLee** [comment]
Basically, every project has the following Bitrise.yml:

```yaml
---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
trigger_map:
- pull_request_source_branch: "*"
  workflow: open_source_projects
workflows:
  open_source_projects:
    steps:
    - activate-ssh-key:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone: {}
    - script:
        title: Continue from WeTransfer-iOS-CI repo
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            bitrise run --config ./Submodules/WeTransfer-iOS-CI/Bitrise/bitrise.yml "${BITRISE_TRIGGERED_WORKFLOW_ID}"
```

They all switch over to our shared CI solution which you can find here:
https://github.com/WeTransfer/WeTransfer-iOS-CI/blob/master/Bitrise/bitrise.yml

The only difference between the working and non-working project is the fact that one is private and the other one is public.

> You are also caching CocoaPods correct?

As you can see from the Bitrise.yml configurations, we're not using CocoaPods. We're caching brews, GEMs, and submodules.

I hope this helps, it would be great to have caching on our open-sourced public projects as well!
